'use strict';

/*
 * Property 7: A required-email failure blocks its operation and never leaks
 * internal detail (design.md — Correctness Properties).
 *
 *   For any operation that requires an email (verification send on
 *   register/resend, submission confirmation), if the Email_Service delivery
 *   fails, the System SHALL NOT report that operation as successful, SHALL
 *   record the failure in the email log, and the response returned to the
 *   applicant SHALL NOT contain internal error detail.
 *
 * Validates: Requirements 13.3
 *
 * Strategy
 * --------
 * A single stateful transport is injected via makeFactoryApp. Its two required
 * sends (`sendVerificationCode`, `sendConfirmation`) throw a rejection whose
 * Error message carries a *distinctive internal detail string* generated by
 * fast-check (a UUID-tagged SMTP-style error). Because the string is unique per
 * iteration and clearly "internal", asserting that it is absent from the
 * response body is a meaningful leak check, while its presence in the
 * `email_log.error` column proves the transport really failed with that detail.
 *
 * Each iteration drives all three required-email operations and asserts, for
 * each, that (a) the operation is NOT reported successful (HTTP 502, never a
 * 2xx / success flag), (b) an `email_log` row with status='failed' carrying the
 * distinctive detail exists (queried from app.locals.db), and (c) the
 * distinctive detail does NOT appear anywhere in the response body.
 *
 * The server attempts the verification send BEFORE persisting on register (so a
 * failed register creates no user) and BEFORE replacing the code on resend; the
 * application flow persists first and then, on a failed confirmation send,
 * returns 502 that still surfaces the stored confirmation number. To keep the
 * >= 100 iterations fast (bcrypt cost 12 is deliberately slow), verified/​
 * unverified accounts and their sessions used by the resend and confirmation
 * paths are seeded directly into the database and driven via the session cookie.
 */

const { test } = require('node:test');
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const request = require('supertest');
const fc = require('fast-check');

const { makeFactoryApp } = require('./helpers');

// ---- distinctive internal-detail generator --------------------------------
// A clearly-internal, unique-per-iteration error string. The UUID guarantees a
// value that will not incidentally occur in a generic applicant-facing message,
// so "detail absent from the response" is a real signal rather than luck.
const distinctiveDetail = fc
  .uuid()
  .map((u) => `SMTP 535 auth failed relay=mail.internal.ualr.edu user=svc-mailer secret-token-${u}`);

// ---- helpers --------------------------------------------------------------

const PDF_BYTES = Buffer.from('%PDF-1.4\n%%EOF\n');

function validFormFields() {
  return {
    first_name: 'Ada',
    last_name: 'Lovelace',
    institution: 'Example College',
    institution_type: 'community_college',
    major: 'Computer Science',
    year: 'sophomore',
    theme1: 'ai',
    ref1_name: 'Grace Hopper',
    ref1_email: 'grace@example.edu',
    ref2_name: 'Alan Turing',
    ref2_email: 'alan@example.org',
    citizenship: 'us_citizen',
    statement: 'a'.repeat(1300),
  };
}

// Seed a user + session row directly (no bcrypt) and return the session token.
function seedSession(db, email, { verified }) {
  const info = db
    .prepare(
      `INSERT INTO users (email, password_hash, name, affiliation, verified, verify_code, created_at)
       VALUES (?,?,?,?,?,?,?)`
    )
    .run(email, 'x'.repeat(60), 'Seed User', 'external', verified ? 1 : 0, verified ? null : '000000', new Date().toISOString());
  const token = crypto.randomBytes(32).toString('hex');
  const expires = new Date(Date.now() + 7 * 864e5).toISOString();
  db.prepare('INSERT INTO sessions (token, user_id, expires_at) VALUES (?,?,?)').run(token, info.lastInsertRowid, expires);
  return token;
}

// A failed email_log row for this recipient/kind carrying exactly the detail the
// transport rejected with. The server stores err.message verbatim in `error`.
function failedLogRow(db, email, kind, detail) {
  return db
    .prepare(`SELECT * FROM email_log WHERE to_email = ? AND kind = ? AND status = 'failed' AND error = ?`)
    .get(email, kind, detail);
}

// Assert an operation was NOT reported successful and did not leak the detail.
function assertBlockedAndClean(res, detail, label) {
  // (a) not success: an error status, never a 2xx / success flag.
  assert.ok(res.status >= 400, `${label}: expected an error status, got ${res.status}`);
  assert.equal(res.status, 502, `${label}: required-email failure should surface as 502, got ${res.status}`);

  // (c) the distinctive internal detail must not appear anywhere in the response.
  const bodyText = `${res.text || ''}\n${JSON.stringify(res.body || {})}`;
  assert.ok(
    !bodyText.includes(detail),
    `${label}: internal error detail leaked into the response body`,
  );
}

// ---------------------------------------------------------------------------

test('Feature: reu-recruitment-site, Property 7: A required-email failure blocks its operation and never leaks internal detail', async () => {
  // A single stateful transport whose failures are toggled per operation and
  // whose rejection message is the current iteration's distinctive detail.
  const state = { detail: '', failVerification: false, failConfirmation: false };
  const transport = {
    sendVerificationCode() {
      if (state.failVerification) throw new Error(state.detail);
    },
    async sendConfirmation() {
      if (state.failConfirmation) throw new Error(state.detail);
    },
  };

  const ctx = makeFactoryApp({ transport });
  const db = ctx.db;

  // Shared unverified account for the resend path (resend never mutates it on
  // failure, so it can be reused across all iterations).
  const resendEmail = 'resend-shared@example.com';
  const resendToken = seedSession(db, resendEmail, { verified: false });

  let n = 0;
  const userCount = db.prepare('SELECT COUNT(*) AS c FROM users WHERE email = ?');

  try {
    await fc.assert(
      fc.asyncProperty(distinctiveDetail, async (detail) => {
        state.detail = detail;
        const i = n++;

        // ---- 1. REGISTER: verification send fails -> blocks, no user, logged ----
        state.failVerification = true;
        state.failConfirmation = false;
        const regEmail = `regfail-${i}@example.edu`;
        const regRes = await request(ctx.app)
          .post('/api/auth/register')
          .send({ email: regEmail, name: 'Reg Fail', password: 'password-123456' });

        assertBlockedAndClean(regRes, detail, 'register');
        // The send is attempted before persisting, so no account is created.
        assert.equal(userCount.get(regEmail).c, 0, 'register: a failed verification send must not create an account');
        const regLog = failedLogRow(db, regEmail, 'verification', detail);
        assert.ok(regLog, 'register: a failed verification email_log row must be written');

        // ---- 2. RESEND: verification send fails -> blocks, logged ----
        state.failVerification = true;
        state.failConfirmation = false;
        const resendRes = await request(ctx.app)
          .post('/api/auth/resend')
          .set('Cookie', `session=${resendToken}`)
          .send({});

        assertBlockedAndClean(resendRes, detail, 'resend');
        const resendLog = failedLogRow(db, resendEmail, 'verification', detail);
        assert.ok(resendLog, 'resend: a failed verification email_log row must be written');

        // ---- 3. APPLICATION CONFIRMATION: confirmation send fails ----
        // Persist-first semantics: the application is stored, then the failed
        // confirmation send yields 502 that still surfaces the confirmation
        // number, logs 'failed', and leaks no detail.
        state.failVerification = false;
        state.failConfirmation = true;
        const applyEmail = `confirm-${i}@example.com`;
        const applyToken = seedSession(db, applyEmail, { verified: true });

        const applyReq = request(ctx.app)
          .post('/api/applications')
          .set('Cookie', `session=${applyToken}`);
        for (const [k, v] of Object.entries(validFormFields())) applyReq.field(k, v);
        applyReq.attach('transcript', PDF_BYTES, { filename: 't.pdf', contentType: 'application/pdf' });
        const applyRes = await applyReq;

        assertBlockedAndClean(applyRes, detail, 'confirmation');
        // The stored confirmation number is still returned (submission not lost).
        assert.match(
          String(applyRes.body.confirmation || ''),
          /^REU27-/,
          'confirmation: the stored confirmation number should still be surfaced',
        );
        const applyLog = failedLogRow(db, applyEmail, 'confirmation', detail);
        assert.ok(applyLog, 'confirmation: a failed confirmation email_log row must be written');
      }),
      { numRuns: 100 },
    );
  } finally {
    ctx.cleanup();
  }
});
